### ISSUE TITLE
컨텍스트 기능

### ISSUE THREAD

**Issue by redgoose-dev** [redgoose-dev/json-editor#22]
컨텍스트의 기능

- change type
- insert
- duplicate
- remove

## change type

타입을 변경하는 기능. 변경 가능한 타입은 다음과 같다.

- object
- array
- string
- number
- boolean
- null

## insert

하위 아이템 추가. object, array 타입에서 사용할 수 있다.

## duplicate

아이템을 복제한다.

## remove

항목을 삭제한다.

## TODO

- [x] 컴포넌트 만들기 (UI)
- [x] 액션 기능들 만들기 - change type
- [x] 액션 기능들 만들기 - insert
- [x] 액션 기능들 만들기 - duplicate
- [x] 액션 기능들 만들기 - remove
